### ISSUE TITLE
只能看见主页的图片，点击进去看不见具体的图片了

### ISSUE THREAD

**Issue by 2012icct** [flyou/Girls#11]

**Comment by ZxJust** [comment]
是的，不是个例

**Comment by hljwang3874149** [comment]
改下目标节点 获取内容就可以了

**Comment by flyou** [comment]
@zxJust @2012icct 已经修复

**Comment by 2012icct** [comment]
@flyou ,我看里面有很多fragment代码都是一样的，这样是不是不太好啊？

**Comment by flyou** [comment]
@2012icct 其实没什么好不好的，只是为了方便通过类名来区分不同的lurl，当然你也可以使用一个类来实现，直接在Fragment时传入参数是一样的

**Comment by 2012icct** [comment]
这样做当然不好，代码的易维护性不太好。如果你这个fragment想增加一个新的功能，你每个fragment都要修改，稍不注意就会漏改或改错。我不是程序员，是个外行。

**Comment by flyou** [comment]
@2012icct 恩恩 很受益
