### ISSUE TITLE
我更想学习下，python爬虫怎么写的

### ISSUE THREAD

**Issue by Freshman111** [flyou/Girls#4]

**Comment by xatgithub** [comment]
不需要腳本，一個命令就能下載整站了。
`wget -c -m -p -K -k -nH --local-encoding=utf-8 --remote-encoding=utf-8 --restrict-file-names=nocontrol --reject-regex=json http://m.xxxiao.com`

**Comment by Freshman111** [comment]
谢谢

**Comment by flyou** [comment]
http://www.zhihu.com/question/20899988
你可以看下这个
